In [6]:
import pandas as pd

df = pd.read_csv('mtcars.csv')

In [8]:
df.head()

Unnamed: 0       vichle_names   mpg  cyl   disp     hp  drat     wt   qsec  \
0           0          Mazda RX4  21.0    6  160.0  110.0  3.90  2.620  16.46   
1           1      Mazda RX4 Wag  21.0    6  160.0  110.0  3.90  2.875  17.02   
2           2         Datsun 710   NaN    4  108.0   93.0  3.85  2.320  18.61   
3           3     Hornet 4 Drive  21.4    6  258.0    NaN  3.08  3.215  19.44   
4           4  Hornet Sportabout  18.7    8  360.0  175.0  3.15  3.440  17.02   

   v_Shape   am  gear  carb  
0      0.0  1.0   4.0     4  
1      0.0  1.0   4.0     4  
2      1.0  1.0   4.0     1  
3      1.0  0.0   3.0     1  
4      0.0  0.0   NaN     2

In [9]:
df.tail()

Unnamed: 0    vichle_names   mpg  cyl   disp     hp  drat     wt  qsec  \
27          27    Lotus Europa  30.4    4   95.1  113.0  3.77  1.513  16.9   
28          28  Ford Pantera L  15.8    8  351.0  264.0  4.22  3.170  14.5   
29          29    Ferrari Dino  19.7    6  145.0  175.0  3.62  2.770  15.5   
30          30   Maserati Bora  15.0    8  301.0  335.0  3.54  3.570  14.6   
31          31      Volvo 142E  21.4    4  121.0  109.0  4.11  2.780  18.6   

    v_Shape   am  gear  carb  
27      1.0  1.0   5.0     2  
28      0.0  1.0   5.0     4  
29      0.0  1.0   5.0     6  
30      0.0  1.0   5.0     8  
31      1.0  1.0   4.0     2

In [10]:
# to print number of rows and columns in the dataFrame

df.shape

(32, 13)

In [11]:
# to print number of rows in the dataFrame

df.shape[0]

32

In [12]:
# get numerical column statistics about the dataFrame

df.describe()

Unnamed: 0        mpg        cyl        disp          hp       drat  \
count   32.000000  30.000000  32.000000   32.000000   31.000000  31.000000   
mean    15.500000  20.076667   6.187500  230.721875  147.870968   3.609032   
std      9.380832   6.196366   1.785922  123.938694   69.363171   0.538766   
min      0.000000  10.400000   4.000000   71.100000   52.000000   2.760000   
25%      7.750000  15.275000   4.000000  120.825000   96.000000   3.080000   
50%     15.500000  19.200000   6.000000  196.300000  123.000000   3.700000   
75%     23.250000  22.475000   8.000000  326.000000  180.000000   3.920000   
max     31.000000  33.900000   8.000000  472.000000  335.000000   4.930000   

              wt       qsec    v_Shape         am       gear     carb  
count  32.000000  29.000000  30.000000  28.000000  29.000000  32.0000  
mean    3.217250  17.601379   0.433333   0.428571   3.724138   2.8125  
std     0.978457   1.535459   0.504007   0.503953   0.751026   1.6152  
min     1.513000  14.500000   0.000000   0.000000   3.000000   1.0000  
25%     2.581250  16.870000   0.000000   0.000000   3.000000   2.0000  
50%     3.325000  17.420000   0.000000   0.000000   4.000000   2.0000  
75%     3.610000  18.610000   1.000000   1.000000   4.000000   4.0000  
max     5.424000  20.010000   1.000000   1.000000   5.000000   8.0000

In [13]:
# to get the number (count) of missing values in a dataFrame

df.isna().sum()

Unnamed: 0      0
vichle_names    0
mpg             2
cyl             0
disp            0
hp              1
drat            1
wt              0
qsec            3
v_Shape         2
am              4
gear            3
carb            0
dtype: int64

In [14]:
# to get the ratio of missing values in a data frame

df.isna().mean() * 100

Unnamed: 0       0.000
vichle_names     0.000
mpg              6.250
cyl              0.000
disp             0.000
hp               3.125
drat             3.125
wt               0.000
qsec             9.375
v_Shape          6.250
am              12.500
gear             9.375
carb             0.000
dtype: float64

In [15]:
df.dtypes

Unnamed: 0        int64
vichle_names     object
mpg             float64
cyl               int64
disp            float64
hp              float64
drat            float64
wt              float64
qsec            float64
v_Shape         float64
am              float64
gear            float64
carb              int64
dtype: object

In [17]:
# create a duplicate of the dataFrame

df_copy1 = df.copy()
df_copy2 = df.copy()

df_copy1.head()

Unnamed: 0       vichle_names   mpg  cyl   disp     hp  drat     wt   qsec  \
0           0          Mazda RX4  21.0    6  160.0  110.0  3.90  2.620  16.46   
1           1      Mazda RX4 Wag  21.0    6  160.0  110.0  3.90  2.875  17.02   
2           2         Datsun 710   NaN    4  108.0   93.0  3.85  2.320  18.61   
3           3     Hornet 4 Drive  21.4    6  258.0    NaN  3.08  3.215  19.44   
4           4  Hornet Sportabout  18.7    8  360.0  175.0  3.15  3.440  17.02   

   v_Shape   am  gear  carb  
0      0.0  1.0   4.0     4  
1      0.0  1.0   4.0     4  
2      1.0  1.0   4.0     1  
3      1.0  0.0   3.0     1  
4      0.0  0.0   NaN     2

In [18]:
df_copy1.dtypes

Unnamed: 0        int64
vichle_names     object
mpg             float64
cyl               int64
disp            float64
hp              float64
drat            float64
wt              float64
qsec            float64
v_Shape         float64
am              float64
gear            float64
carb              int64
dtype: object

In [19]:
# replace missing values with mean
df_copy1 = df_copy1.fillna(df_copy1.mean)

df_copy1.isna().sum()

Unnamed: 0      0
vichle_names    0
mpg             0
cyl             0
disp            0
hp              0
drat            0
wt              0
qsec            0
v_Shape         0
am              0
gear            0
carb            0
dtype: int64

In [20]:
# replace missing values with mode
df_copy2.fillna(df_copy2.mode().iloc[0], inplace=True)

df_copy2.isna().sum()


Unnamed: 0      0
vichle_names    0
mpg             0
cyl             0
disp            0
hp              0
drat            0
wt              0
qsec            0
v_Shape         0
am              0
gear            0
carb            0
dtype: int64

In [22]:
# to separate categorical and numerical columns

categorical_columns = df.select_dtypes(include=['object']).columns
numerical_columns = df.select_dtypes(include=['number']).columns

df_cat = df[categorical_columns]
df_num = df[numerical_columns]

df_cat.head(), df_num.head()

(        vichle_names
 0          Mazda RX4
 1      Mazda RX4 Wag
 2         Datsun 710
 3     Hornet 4 Drive
 4  Hornet Sportabout,
    Unnamed: 0   mpg  cyl   disp     hp  drat     wt   qsec  v_Shape   am  \
 0           0  21.0    6  160.0  110.0  3.90  2.620  16.46      0.0  1.0   
 1           1  21.0    6  160.0  110.0  3.90  2.875  17.02      0.0  1.0   
 2           2   NaN    4  108.0   93.0  3.85  2.320  18.61      1.0  1.0   
 3           3  21.4    6  258.0    NaN  3.08  3.215  19.44      1.0  0.0   
 4           4  18.7    8  360.0  175.0  3.15  3.440  17.02      0.0  0.0   
 
    gear  carb  
 0   4.0     4  
 1   4.0     4  
 2   4.0     1  
 3   3.0     1  
 4   NaN     2  )

In [23]:
name = ['carb', 'milk', 'eggs', 'bicycle']
deg = ['MBA', 'BCA', 'M.Tech', 'MBA']
scr = [90, 40, 80, 98]

dict_xyz = {'name': name, 'deg': deg, 'scr': scr}

df1 = pd.DataFrame(dict_xyz)

df1

name     deg  scr
0     carb     MBA   90
1     milk     BCA   40
2     eggs  M.Tech   80
3  bicycle     MBA   98

In [26]:
df1.index.name

In [28]:
df1.index.name = 'my_index'

In [29]:
df1.index.name

'my_index'

In [30]:
df1

name     deg  scr
my_index                      
0            carb     MBA   90
1            milk     BCA   40
2            eggs  M.Tech   80
3         bicycle     MBA   98

In [404]:
# to save as csv file

df1.to_csv('./file1.csv')

In [405]:
# to save as json file

df1.to_json('./file1.json')

In [31]:
# read json file with pandas

df2 = pd.read_json('./file1.json')

In [32]:
df2

name     deg  scr
0     carb     MBA   90
1     milk     BCA   40
2     eggs  M.Tech   80
3  bicycle     MBA   98

In [2]:
# create 100 samples with 3 features

from sklearn.datasets import make_regression

# n_samples = number of rows
# n_features = number of features you want to generate for this regression
# n_informative = number of features used to build the linear model used to generate the output
# n_target = the number of target features you want to work with
# noise = if you want noise in your values
# coefficient = in linear regression (y = B1X1 + B2X2) here B1 & B2 is the coefficient
# random state = if you want to use random data in your regression values

features, target, coefficient = make_regression(
    n_samples=100, n_features=3, n_informative=3, n_targets=1, noise=0.0, coef=True, random_state=1
)

print('Feature Matrix  \n', features[:3])
print('\nTarget Vector  \n', target[:3])
print('\nCoefficient Vector  \n', coefficient[:3])


Feature Matrix  
 [[ 1.29322588 -0.61736206 -0.11044703]
 [-2.793085    0.36633201  1.93752881]
 [ 0.80186103 -0.18656977  0.0465673 ]]

Target Vector  
 [-10.37865986  25.5124503   19.67705609]

Coefficient Vector  
 [44.19042807 98.97517077 58.15774073]


In [5]:
type(coefficient)

numpy.ndarray