In [23]:
# generating data for regression

from sklearn.datasets import make_regression, make_classification

features, target, coefficients = make_regression(
    n_samples=100,
    n_features=3,
    n_informative=3,
    n_targets=1,
    noise=0.0,
    coef=1,
    random_state=1
)

print(features[:3], "\n")

print(target[:3], "\n")

print(coefficients)

[[ 1.29322588 -0.61736206 -0.11044703]
 [-2.793085    0.36633201  1.93752881]
 [ 0.80186103 -0.18656977  0.0465673 ]] 

[-10.37865986  25.5124503   19.67705609] 

[44.19042807 98.97517077 58.15774073]


#### Explanation:

here we've 3 features and 1 target <br /><br />
and out of these 3 features we want to use the whole 3 to build our model hence <br /> <br />
`n_informative=3`

In [31]:
# generating data for classification

features, target = make_classification(
    n_samples=100,
    n_features=3,
    n_informative=3,
    n_redundant=0,
    n_classes=2,
    weights=[0.25, 0.75],
    random_state=1,
)

print('Feature Matrix  \n', features[:3])
print('\nTarget Vector  \n', target[:3])

Feature Matrix  
 [[ 1.06354768 -1.42632219  1.02163151]
 [ 0.23156977  1.49535261  0.33251578]
 [ 0.15972951  0.83533515 -0.40869554]]

Target Vector  
 [1 0 0]


In [36]:
# to check the data type for features and target

print(type(features), "\n")
print(type(target), "\n")

<class 'numpy.ndarray'> 

<class 'numpy.ndarray'> 



In [50]:
# create a dataframe including features and target

import pandas as pd
import numpy as np

data = np.hstack((features, np.reshape(target, (-1, 1))))

df = pd.DataFrame(data, columns=['a', 'b', 'c', 'd'])
df

a         b         c    d
0   1.063548 -1.426322  1.021632  1.0
1   0.231570  1.495353  0.332516  0.0
2   0.159730  0.835335 -0.408696  0.0
3  -0.706121 -1.032810  1.394780  1.0
4   0.844490 -0.619972  1.087911  1.0
..       ...       ...       ...  ...
95  1.106411 -1.615516  1.603296  1.0
96 -2.438623 -1.784630  0.500376  1.0
97 -1.304690 -1.652926  0.992340  1.0
98  1.190208 -0.961064  0.292125  1.0
99 -1.088047  0.828038 -0.566882  0.0

[100 rows x 4 columns]

In [53]:
# create a dataframe including features and target

import pandas as pd

df = pd.DataFrame(features, columns=['feature_a', 'feature_b', 'feature_c'])
df['target'] = target

df

feature_a  feature_b  feature_c  target
0    1.063548  -1.426322   1.021632       1
1    0.231570   1.495353   0.332516       0
2    0.159730   0.835335  -0.408696       0
3   -0.706121  -1.032810   1.394780       1
4    0.844490  -0.619972   1.087911       1
..        ...        ...        ...     ...
95   1.106411  -1.615516   1.603296       1
96  -2.438623  -1.784630   0.500376       1
97  -1.304690  -1.652926   0.992340       1
98   1.190208  -0.961064   0.292125       1
99  -1.088047   0.828038  -0.566882       0

[100 rows x 4 columns]

In [66]:
from sklearn.datasets import make_blobs

# generating data for clustering

features, classes = make_blobs(
    n_samples=100,
    centers=3,
    n_features=2,
    random_state=0
)

print('Feature Matrix  \n', features[:3])
print('\nTarget Vector  \n', classes[:3])

Feature Matrix  
 [[2.63185834 0.6893649 ]
 [0.08080352 4.69068983]
 [3.00251949 0.74265357]]

Target Vector  
 [1 0 1]


In [67]:
df = pd.DataFrame(features, columns=['features1', 'features2'])
df['cluster_id'] = classes

df

features1  features2  cluster_id
0    2.631858   0.689365           1
1    0.080804   4.690690           0
2    3.002519   0.742654           1
3   -0.637628   4.091047           0
4   -0.072283   2.883769           0
..        ...        ...         ...
95  -0.338874   3.234825           2
96   1.289338   3.449692           0
97   1.840706   3.561622           0
98  -0.901673   1.315825           2
99  -2.752340   3.762245           2

[100 rows x 3 columns]

In [68]:
import plotly.express as px

fig = px.scatter(df, x='features1', y='features2', color='cluster_id')
fig.show()

In [117]:
# using sqlite3 in python

# import sqlite3
import sqlite3

# establish a connection to sqlite3
conn = sqlite3.connect('example.db')

# create cursor object
cursor = conn.cursor()

In [118]:
# create a table

query = '''CREATE TABLE EMPLOYEE(
    FIRST_NAME  CHAR(20)    NOT NULL,
    LAST_NAME   CHAR(20)    NOT NULL,
    AGE         INT         NOT NULL,
    SEX         CHAR(1),
    INCOME      FLOAT
)'''

cursor.execute(query)
conn.commit()

In [119]:
# a lookup on the table
query = '''SELECT * FROM EMPLOYEE'''

cursor.execute(query)
conn.commit()

print(cursor.description)

(('FIRST_NAME', None, None, None, None, None, None), ('LAST_NAME', None, None, None, None, None, None), ('AGE', None, None, None, None, None, None), ('SEX', None, None, None, None, None, None), ('INCOME', None, None, None, None, None, None))


In [143]:
# creating multiple insert into table

cursor.execute('''
    INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, AGE, SEX, INCOME) 
    VALUES('John', 'Smith', 23, 'M', 3000)
''')
cursor.execute('''
    INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, AGE, SEX, INCOME) 
    VALUES('Janet', 'DOe', 123, 'M', 3000)
''')
cursor.execute('''
    INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, AGE, SEX, INCOME) 
    VALUES('Xander', 'Phlip', 30, 'F', 45000)
''')
cursor.execute('''
    INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, AGE, SEX, INCOME) 
    VALUES('Ola', 'Mide', 15, 'M', 900000)
''')
cursor.execute('''
    INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, AGE, SEX, INCOME) 
    VALUES('Akin', 'Olu', 28, 'M', 3000)
''')
cursor.execute('''
    INSERT INTO EMPLOYEE(FIRST_NAME, LAST_NAME, AGE, SEX, INCOME) 
    VALUES('Emmanuel', 'Akinyemi', 28, 'M', 10000)
''')

conn.commit()

In [144]:
# a lookup on the table
query = '''SELECT * FROM EMPLOYEE'''

cursor.execute(query)
conn.commit()

result = cursor.fetchall()

print(result)

[('John', 'Smith', 24, 'M', 3000.0), ('Ola', 'Mide', 16, 'M', 900000.0), ('John', 'Smith', 23, 'M', 3000.0), ('Janet', 'DOe', 123, 'M', 3000.0), ('Xander', 'Phlip', 30, 'F', 45000.0), ('Ola', 'Mide', 15, 'M', 900000.0), ('Akin', 'Olu', 28, 'M', 3000.0), ('Emmanuel', 'Akinyemi', 28, 'M', 10000.0)]


In [145]:
# insert many

data = [
    ('Chadwick', 'Clerk', 26, 'M', 3000),
    ('Gotham', 'Test', 26, 'M', 3000),
    ('Sourab', 'Test', 26, 'M', 3000),
    ('Sarala', 'Test', 26, 'M', 3000),
]

cursor.executemany('''
    INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, AGE, SEX, INCOME) 
    VALUES (?, ?, ?, ?, ?) 
''', data)

conn.commit()

In [146]:
# a lookup on the table
query = '''SELECT * FROM EMPLOYEE'''

cursor.execute(query)
conn.commit()

result = cursor.fetchall()

print(result)

[('John', 'Smith', 24, 'M', 3000.0), ('Ola', 'Mide', 16, 'M', 900000.0), ('John', 'Smith', 23, 'M', 3000.0), ('Janet', 'DOe', 123, 'M', 3000.0), ('Xander', 'Phlip', 30, 'F', 45000.0), ('Ola', 'Mide', 15, 'M', 900000.0), ('Akin', 'Olu', 28, 'M', 3000.0), ('Emmanuel', 'Akinyemi', 28, 'M', 10000.0), ('Chadwick', 'Clerk', 26, 'M', 3000.0), ('Gotham', 'Test', 26, 'M', 3000.0), ('Sourab', 'Test', 26, 'M', 3000.0), ('Sarala', 'Test', 26, 'M', 3000.0)]


In [147]:
cursor.execute('''SELECT * FROM EMPLOYEE''')
result = cursor.fetchone()

print(result)

('John', 'Smith', 24, 'M', 3000.0)


In [148]:
result = cursor.fetchmany(2)
print(result)

[('Ola', 'Mide', 16, 'M', 900000.0), ('John', 'Smith', 23, 'M', 3000.0)]


In [149]:
result = cursor.fetchall()
print(result)

[('Janet', 'DOe', 123, 'M', 3000.0), ('Xander', 'Phlip', 30, 'F', 45000.0), ('Ola', 'Mide', 15, 'M', 900000.0), ('Akin', 'Olu', 28, 'M', 3000.0), ('Emmanuel', 'Akinyemi', 28, 'M', 10000.0), ('Chadwick', 'Clerk', 26, 'M', 3000.0), ('Gotham', 'Test', 26, 'M', 3000.0), ('Sourab', 'Test', 26, 'M', 3000.0), ('Sarala', 'Test', 26, 'M', 3000.0)]


In [150]:
# update column value

query = '''UPDATE EMPLOYEE SET AGE = AGE + 1 WHERE SEX = 'M';'''
cursor.execute(query)
conn.commit()

In [151]:
# a lookup on the table
query = '''SELECT * FROM EMPLOYEE'''

cursor.execute(query)
conn.commit()

result = cursor.fetchall()

print(result)

[('John', 'Smith', 25, 'M', 3000.0), ('Ola', 'Mide', 17, 'M', 900000.0), ('John', 'Smith', 24, 'M', 3000.0), ('Janet', 'DOe', 124, 'M', 3000.0), ('Xander', 'Phlip', 30, 'F', 45000.0), ('Ola', 'Mide', 16, 'M', 900000.0), ('Akin', 'Olu', 29, 'M', 3000.0), ('Emmanuel', 'Akinyemi', 29, 'M', 10000.0), ('Chadwick', 'Clerk', 27, 'M', 3000.0), ('Gotham', 'Test', 27, 'M', 3000.0), ('Sourab', 'Test', 27, 'M', 3000.0), ('Sarala', 'Test', 27, 'M', 3000.0)]


In [152]:
# Delete row from table

query = '''DELETE FROM EMPLOYEE WHERE AGE > 100'''
cursor.execute(query)
conn.commit()

In [153]:
# a lookup on the table
query = '''SELECT * FROM EMPLOYEE'''

cursor.execute(query)
conn.commit()

result = cursor.fetchall()

print(result)

[('John', 'Smith', 25, 'M', 3000.0), ('Ola', 'Mide', 17, 'M', 900000.0), ('John', 'Smith', 24, 'M', 3000.0), ('Xander', 'Phlip', 30, 'F', 45000.0), ('Ola', 'Mide', 16, 'M', 900000.0), ('Akin', 'Olu', 29, 'M', 3000.0), ('Emmanuel', 'Akinyemi', 29, 'M', 10000.0), ('Chadwick', 'Clerk', 27, 'M', 3000.0), ('Gotham', 'Test', 27, 'M', 3000.0), ('Sourab', 'Test', 27, 'M', 3000.0), ('Sarala', 'Test', 27, 'M', 3000.0)]


In [ ]:
# DELETE one column from the table
# alter table

In [ ]:
# rename column sex to gender
# rename the table to my name 'Emmanuel'